version: '3'
services:
  pgcontainer:
    container_name: pgcontainer
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verysecure
      POSTGRES_DB: web_project_car_company