version: '3'
services:
  pgcontainer:
    container_name: pgcontainer
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verysecure
      POSTGRES_DB: web_project_car_company

  backendcontainer:
    container_name: backendcontainer
    image: backendimage
    restart: always
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - pgcontainer

  frontendcontainer:
    container_name: frontendcontainer
    image: frontendimage
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backendcontainer

